# Generated by Django 4.2 on 2024-04-04 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="тег мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="дата обновления"
                    ),
                ),
                (
                    "registration_open",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата открытия регистрации"
                    ),
                ),
                (
                    "registration_close",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата закрытия регистрации"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="дата начала мероприятия",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="дата окончания мероприятия",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="описание"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="город мероприятия",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        upload_to="events_pictures/",
                        verbose_name="обложка мероприятия",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="адрес мероприятия"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("online", "онлайн"), ("offline", "оффлайн")],
                        max_length=7,
                        verbose_name="формат мероприятия",
                    ),
                ),
                (
                    "stream_link",
                    models.URLField(
                        blank=True, default="", verbose_name="ссылка на трансляцию"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="организатор",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_moderated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="модератор",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="events.eventtags", verbose_name="тег"),
                ),
            ],
            options={
                "verbose_name": "мероприятие",
                "verbose_name_plural": "мероприятия",
                "ordering": ("id", "created_at", "creator"),
            },
        ),
    ]
