# Generated by Django 4.2 on 2024-04-09 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-date_start"],
                "verbose_name": "Доклад",
                "verbose_name_plural": "Доклады",
            },
        ),
        migrations.RenameField(
            model_name="report",
            old_name="end_at",
            new_name="date_end",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="start_at",
            new_name="date_start",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="short_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="position",
            new_name="speaker_title",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="topic",
            new_name="title",
        ),
    ]
