# Generated by Django 4.2 on 2024-04-12 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_report_options_rename_end_at_report_date_end_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-start_at"],
                "verbose_name": "Доклад",
                "verbose_name_plural": "Доклады",
            },
        ),
        migrations.RenameField(
            model_name="report",
            old_name="date_end",
            new_name="end_at",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="speaker_title",
            new_name="position",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="description",
            new_name="short_description",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="date_start",
            new_name="start_at",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="title",
            new_name="topic",
        ),
        migrations.AddField(
            model_name="registration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания",
            ),
            preserve_default=False,
        ),
    ]
