# Generated by Django 4.2 on 2024-04-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_updated_at_alter_events_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название доклада')),
                ('description', models.TextField(max_length=500, unique=True, verbose_name='описание долкада')),
                ('date_start', models.DateTimeField(db_index=True, default=None, verbose_name='дата начала доклада')),
                ('date_end', models.DateTimeField(db_index=True, default=None, verbose_name='дата окончания доклада')),
                ('speaker', models.CharField(max_length=50, verbose_name='Фамилиия и имя спикера')),
                ('speaker_title', models.CharField(max_length=50, verbose_name='Должность спикера')),
                ('speaker_photo', models.ImageField(blank=True, upload_to='speakers_pictures/', verbose_name='Фотография спикера')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_at_event', to='events.events', verbose_name='доклад')),
            ],
            options={
                'verbose_name': 'Доклад',
                'verbose_name_plural': 'Доклады',
                'ordering': ['-date_start'],
            },
        ),
    ]
