# Generated by Django 4.2 on 2024-04-14 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_report_options_rename_date_end_report_end_at_and_more"),
        ("events", "0003_favorites"),
    ]

    operations = []
