# Generated by Django 4.2 on 2024-04-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_merge_20240414_1646"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorites",
            options={
                "verbose_name": "избранное мероприятие",
                "verbose_name_plural": "избранные мероприятия",
            },
        ),
        migrations.AlterField(
            model_name="favorites",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_favorite",
                to="events.events",
                verbose_name="мероприятие",
            ),
        ),
    ]
