# Generated by Django 4.2 on 2024-04-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-start_at'], 'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_end',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='speaker_title',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_start',
            new_name='start_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='topic',
        ),
    ]
