# Generated by Django 4.2 on 2024-04-09 11:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="дата обновления"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=150, verbose_name="Пароль пользователя"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Имя пользователя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=150, verbose_name="Фамилия пользователя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        verbose_name="Номер телефона пользователя",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attendee", "Участник"),
                            ("organizer", "Организатор"),
                            ("moderator", "Модератор"),
                        ],
                        default="attendee",
                        max_length=150,
                        verbose_name="Пользовательская роль",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["-id"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUserFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_ev_online",
                    models.BooleanField(default=False, verbose_name="Онлайн событие"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Город проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильтр пользователя",
                "verbose_name_plural": "Фильтры пользователей",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Уникальный слаг")),
            ],
            options={
                "verbose_name": "Направление работы",
                "verbose_name_plural": "Направления работы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecializationsInFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs_in_filter",
                        to="users.customuserfilter",
                        verbose_name="Фильтр",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.specialization",
                        verbose_name="Направления в фильтре.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направления работы в фильтре",
                "verbose_name_plural": "Направления работы в фильтрах",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="CustomUserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ev_notification_start",
                    models.BooleanField(
                        default=False, verbose_name="Уведомлять о начале событий"
                    ),
                ),
                (
                    "ev_notification_new",
                    models.BooleanField(
                        default=False, verbose_name="Уведомлять о новых событиях"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пользователя",
                "verbose_name_plural": "Настройки пользователей",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="CustomUserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="users/images/",
                        verbose_name="Фото",
                    ),
                ),
                ("job", models.CharField(max_length=150, verbose_name="Место работы")),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("0-1", "0-1 год"),
                            ("1-3", "1-3 года"),
                            ("3-5", "3-5 лет"),
                            ("5-10", "5-10 лет"),
                            ("10+", "Больше 10 лет"),
                        ],
                        default="0-1",
                        max_length=20,
                        verbose_name="Опыт работы",
                    ),
                ),
                (
                    "user_agree_personal_info",
                    models.BooleanField(
                        default=False, verbose_name="Согласие на передачу данных"
                    ),
                ),
                (
                    "user_agree_publish_cv",
                    models.BooleanField(
                        default=False, verbose_name="Согласие на публикацию резюме"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_info",
                        to="users.specialization",
                        verbose_name="Направление работы",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп. инфо о пользователе",
                "verbose_name_plural": "Доп. инфо о пользователях",
                "ordering": ["-pk"],
            },
        ),
        migrations.AddField(
            model_name="customuserfilter",
            name="specialization",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_filter",
                through="users.SpecializationsInFilter",
                to="users.specialization",
                verbose_name="Направление работы",
            ),
        ),
        migrations.AddField(
            model_name="customuserfilter",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filter",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
