# Generated by Django 4.2 on 2024-04-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=254, unique=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
