# Generated by Django 4.2 on 2024-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Уникальный слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип события для уведомления",
                "verbose_name_plural": "Типы события для уведомления",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="NotificationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Уникальный слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип уведомления",
                "verbose_name_plural": "Типы уведомления",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Уникальный слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Время уведомления",
                "verbose_name_plural": "Время уведомления",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="customuserinfo",
            name="custom_experience",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Другой опыт работы"
            ),
        ),
        migrations.AddField(
            model_name="customuserinfo",
            name="user_agree_publish_media",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на публикацию фото/видео"
            ),
        ),
        migrations.AlterField(
            model_name="customuserinfo",
            name="experience",
            field=models.CharField(
                choices=[
                    ("0", "Нет опыта"),
                    ("1", "От 1 года"),
                    ("3", "От 3 лет"),
                    ("5", "От 5 лет"),
                    ("other", "Другое"),
                ],
                default="0",
                max_length=20,
                verbose_name="Опыт работы",
            ),
        ),
        migrations.AddField(
            model_name="customusersettings",
            name="ev_notification_method",
            field=models.ManyToManyField(
                related_name="settings",
                to="users.notificationmethod",
                verbose_name="Способ уведомления для событий",
            ),
        ),
        migrations.AddField(
            model_name="customusersettings",
            name="ev_notification_start_time",
            field=models.ManyToManyField(
                related_name="settings",
                to="users.notificationtime",
                verbose_name="Время уведомлений",
            ),
        ),
        migrations.AddField(
            model_name="customusersettings",
            name="ev_type_notification",
            field=models.ManyToManyField(
                related_name="settings",
                to="users.notificationeventtype",
                verbose_name="Тип события для уведомлений",
            ),
        ),
    ]
