# Generated by Django 4.2 on 2024-04-05 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuserfilter_specialization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specializationsinfilter",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Направления работы в фильтре",
                "verbose_name_plural": "Направления работы в фильтрах",
            },
        ),
        migrations.AddField(
            model_name="specializationsinfilter",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_specializations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="customuserfilter",
            name="is_ev_online",
            field=models.BooleanField(default=False, verbose_name="Онлайн событие"),
        ),
        migrations.AlterField(
            model_name="customuserinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="customusersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
