# Generated by Django 4.2 on 2024-04-05 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_specializationsinfilter_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specializationsinfilter",
            name="user",
        ),
    ]
