# Generated by Django 4.2 on 2024-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_specializationsinfilter_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=15, verbose_name="Номер телефона пользователя"
            ),
        ),
    ]
